---
#---------------------------
# Hexo Theme Simple
# Author: isYangs
# Github:
#
# é…ç½®æŒ‡å—:
# ä½ å¯ä»¥ä»æŒ‡å—ä¸­è·å¾—æ›´è¯¦ç»†çš„è¯´æ˜
#
# Guide:
# You can get more detailed help from the guide
#---------------------------

# ç«™ç‚¹æ ‡é¢˜
# Tip: æ ¹ç›®å½•ä¸‹çš„ _config.yml ä¸­è®¾ç½®åï¼Œæ­¤å¤„ä¸å†ç”Ÿæ•ˆ
title: Simple ä¸»é¢˜æ¼”ç¤º

# ç«™ç‚¹å‰¯æ ‡é¢˜
# Tip: æ ¹ç›®å½•ä¸‹çš„ _config.yml ä¸­è®¾ç½®åï¼Œæ­¤å¤„ä¸å†ç”Ÿæ•ˆ
subtitle: 'A simple theme for Hexo'

# ç«™ç‚¹å…³é”®è¯
# Tip: æ ¹ç›®å½•ä¸‹çš„ _config.yml ä¸­è®¾ç½®åï¼Œæ­¤å¤„ä¸å†ç”Ÿæ•ˆ
keywords: 'hexo,theme,simple'

# ç”¨äºæµè§ˆå™¨æ ‡ç­¾çš„å›¾æ ‡
favicon: /favicon.ico

# å¼ºåˆ¶æ‰€æœ‰é“¾æ¥å‡çº§ä¸º HTTPSï¼ˆé€‚ç”¨äºå›¾ç‰‡ç­‰èµ„æºå‡ºç° HTTP æ··å…¥æŠ¥é”™ï¼‰
force_https: false # true | false

# ç½‘ç«™ä½œè€…ä¿¡æ¯
author:
    # ä½œè€…åç§°
    name: isYangs

    # ä½œè€…å¤´åƒï¼Œå¯ä»¥æ˜¯ç›¸å¯¹è·¯å¾„æˆ–å¤–ç«™çš„ç»å¯¹è·¯å¾„
    avatar: https://a.xuewuzhibu.cn/8/655c9835780a0-8.jpg

    # ä½œè€…ç®€ä»‹
    intro: 'ä¸€ä¸ªå¾ˆæ‡’çš„å‰ç«¯Bugæ„é€ å¸ˆ'

    # ä½œè€…æè¿°
    description: <div>åœ¨è¿™é‡Œæœ‰å…³äºæˆ‘å¯¹<b> å‰ç«¯å¼€å‘ UIè®¾è®¡ </b>çš„ä¸€äº›é—®é¢˜å’Œä¸åŒçš„çœ‹æ³•ã€‚<br><br>å¸Œæœ›ä½ èƒ½ä»è¿™é‡Œçš„æ–‡ç« è·å¾—ä¸€äº›å¸®åŠ©ï¼Œå¦‚æœèƒ½å¸®åŠ©åˆ°ä½ æˆ‘å¾ˆè£å¹¸ï¼</div>

    # ä½œè€…ç½‘å€
    link: /about # ç«™å†…åœ°å€ /about | ç½‘å€

    # ä½œè€…æ ‡ç­¾
    tags:
        - ğŸ’» å‰ç«¯Bugæ„é€ å¸ˆ
        - ğŸ¤–ï¸ æ•°ç ç§‘æŠ€çˆ±å¥½è€…
        - ğŸ‘¨â€ğŸ’»â€ é‡åº¦ç†¬å¤œå†™ä»£ç 
        - ğŸ” åˆ†äº«ä¸çƒ­å¿ƒå¸®åŠ©
        - i-logos-hexo || Simple ä¸»é¢˜ä½œè€…

    # ä½œè€…ç¤¾äº¤ä¿¡æ¯
    social:
        github: isyangs || i-mdi-github
        bilibili: 405322353 || i-ri-bilibili-fill
        qq: 750837279 || i-mdi-qqchat

# ä¸»èœå•å¯¼èˆª
menu:
    é¦–é¡µ: /
    å½’æ¡£: /archives
    æ ‡ç­¾: /tags
    åˆ†ç±»: /categories
    å‹é“¾: /links
    å…³äº: /about
    äºŒçº§å¯¼èˆª:
        - äºŒçº§å¯¼èˆª1: /test1
        - äºŒçº§å¯¼èˆª2: /test2
        - äºŒçº§å¯¼èˆª3: /test3

# æœç´¢åŠŸèƒ½
# Tip: åŸºäº hexo-generator-search æ’ä»¶ï¼Œè‹¥å·²å®‰è£…å…¶ä»–æœç´¢æ’ä»¶è¯·å…³é—­æ­¤åŠŸèƒ½ï¼Œä»¥é¿å…ç”Ÿæˆå¤šä½™çš„ç´¢å¼•æ–‡ä»¶
search:
    # æœç´¢ç´¢å¼•æ–‡ä»¶çš„è·¯å¾„ï¼Œå¯ä»¥æ˜¯ç›¸å¯¹è·¯å¾„æˆ–å¤–ç«™çš„ç»å¯¹è·¯å¾„
    path: /local-search.xml

    # æ–‡ä»¶ç”Ÿæˆåœ¨æœ¬åœ°çš„ä½ç½®ï¼Œå¿…é¡»æ˜¯ç›¸å¯¹è·¯å¾„
    generate_path: /local-search.xml

    # æœç´¢çš„èŒƒå›´
    field: post # post | page | all

    # æœç´¢æ˜¯å¦æ‰«ææ­£æ–‡
    content: true # true | false

# é¦–é¡µè½®æ’­å›¾ï¼Œè‹¥ä¸éœ€è¦è¯·è®¾ç½®ä¸º false
slide:
    # æ˜¯å¦å¼€å¯è½®æ’­
    enable: true # true | false

    # æ˜¯å¦å¼€å¯è½®æ’­å›¾å€’è®¡æ—¶
    countdown: true # true | false

    # è½®æ’­å›¾çš„æ ‡é¢˜
    title:
        # - 'Simple ä¸»é¢˜æ¼”ç¤º'
        - 'Simple ä¸»é¢˜æ–‡æ¡£'
        - 'Simple ä¸»é¢˜å®‰è£…'

    # è½®æ’­å›¾çš„é“¾æ¥
    link:
        # - '/'
        - '/'
        - '/'
    # è½®æ’­å›¾çš„å›¾ç‰‡
    image:
        # - https://a.xuewuzhibu.cn/8/655ccc43de410-8.jpg
        - https://a.xuewuzhibu.cn/8/655cccae25d4f-8.jpg
        - https://a.xuewuzhibu.cn/8/655ccc54a4729-8.png

# è½®æ’­æ—ä¸¤æ å†…å®¹
slide_aside:
    # æ˜¯å¦å¼€å¯
    enable: true # true | false

    # æ ‡é¢˜ æœ€å¤šä¸ºä¸¤ä¸ª
    title:
        - 'Simple ä¸»é¢˜'
        - 'Simple ä¸»é¢˜æ–‡æ¡£'

    # é“¾æ¥ æœ€å¤šä¸ºä¸¤ä¸ª
    link:
        - '/'
        - '/'

    # å›¾ç‰‡ æœ€å¤šä¸ºä¸¤ä¸ª
    image:
        - https://a.xuewuzhibu.cn/8/655ccc54a4729-8.png
        - https://a.xuewuzhibu.cn/8/655cccae25d4f-8.jpg

# é¦–é¡µåŠ¨æ€åˆ†ç±»æ¡
dynamic_category:
    # æ˜¯å¦å¼€å¯åŠ¨æ€åˆ†ç±»æ¡
    enable: true # true | false

    # åŠ¨æ€åˆ†ç±»æ¡æ˜¾ç¤ºåˆ†ç±»æ•°é‡ (0 è¡¨ç¤ºæ˜¾ç¤ºæ‰€æœ‰åˆ†ç±»)
    limit: 0

# æ–‡ç« é¡µ
post:
    # æ–‡ç« é¡µé¢çš„é»˜è®¤å°é¢å›¾
    # Tip: å½“æ²¡æœ‰æŒ‡å®š index_img æ—¶ä¼šä½¿ç”¨è¯¥å›¾ç‰‡ï¼Œè‹¥ä¸¤è€…éƒ½ä¸ºç©ºåˆ™ä¸æ˜¾ç¤ºä»»ä½•å›¾ç‰‡
    banner_img: /img/default.png
    # é»˜è®¤å°é¢å›¾çš„é«˜åº¦ï¼Œå•ä½ä¸º px
    banner_img_height: 70

    # æ–‡ç« åœ¨é¦–é¡µçš„é»˜è®¤å°é¢å›¾
    # Tip: å½“æ²¡æœ‰æŒ‡å®š index_img æ—¶ä¼šä½¿ç”¨è¯¥å›¾ç‰‡ï¼Œè‹¥ä¸¤è€…éƒ½ä¸ºç©ºåˆ™ä¸æ˜¾ç¤ºä»»ä½•å›¾ç‰‡
    default_index_img: https://a.xuewuzhibu.cn/8/655ccc54a4729-8.png

    # æ–‡ç« æ ‡é¢˜ä¸‹æ–¹çš„å…ƒä¿¡æ¯
    meta:

    # å­—æ•°ç»Ÿè®¡
    wordcount:
        enable: true

    # ä¼°è®¡é˜…è¯»å…¨æ–‡éœ€è¦çš„æ—¶é•¿
    min2read:
        enable: true
        # æ¯ä¸ªå­—è¯çš„é•¿åº¦ï¼Œå»ºè®®ï¼šä¸­æ–‡ â‰ˆ 2ï¼Œè‹±æ–‡ â‰ˆ 5ï¼Œä¸­è‹±æ··åˆå¯è‡ªè¡Œè°ƒèŠ‚
        awl: 2
        # æ¯åˆ†é’Ÿé˜…è¯»å­—æ•°ï¼Œå¦‚æœå¤§éƒ¨åˆ†æ˜¯æŠ€æœ¯æ–‡ç« å¯é€‚åº¦è°ƒä½
        wpm: 60

    # æµè§ˆé‡è®¡æ•°
    views:
        enable: false
        # ç»Ÿè®¡æ•°æ®æ¥æº
        # Options: busuanzi | leancloud
        source: 'busuanzi'


# å°å·¥å…·
widgets:
    # é‚®ç®±è®¢é˜…ï¼Œæ˜¾ç¤ºåœ¨é¦–é¡µä¾§è¾¹æ 
    email_subscribe:
        enable: true
        # é‚®ç®±è®¢é˜…å¡ç‰‡çš„æ ‡é¢˜
        title: 'çƒ­é—¨èµ„è®¯æŠ€æœ¯å¹²è´§'

        # é‚®ç®±è®¢é˜…å¡ç‰‡çš„æè¿°
        description: 'è¾“å…¥é‚®ç®±ç‚¹å‡»è®¢é˜…æŒ‰é’®ï¼Œå³å¯å¿«äººä¸€æ­¥è·å–æœ€æ–°èµ„è®¯ã€æŠ€æœ¯å¹²è´§ã€è½¯ä»¶èµ„æºç­‰'

        # é‚®ç®±è®¢é˜…å¡ç‰‡çš„æŒ‰é’®æ–‡å­—
        button_text: 'è®¢é˜…'

        # é‚®ç®±è®¢é˜…å¡ç‰‡çš„æŒ‰é’®é“¾æ¥
        button_link: '/'

        # é‚®ç®±è®¢é˜…å¡ç‰‡è¾“å…¥æ¡†çš„æç¤ºæ–‡å­—
        placeholder: 'è¯·è¾“å…¥ä½ çš„é‚®ç®±'

# CDN å‚è€ƒè‡ª Volantis ä¸»é¢˜ï¼Œå³é…ç½®æ–¹æ³•ä¸€æ ·
cdn_system:
    # CDN ä¼˜å…ˆçº§ ä»é«˜åˆ°ä½æ’åº å†™å…¥ priority åˆ—è¡¨å³è¡¨ç¤ºå¯ç”¨(enable)
    priority: [custom, local, cdnjs, npm]
    # ========================================================================
    # cdnæ•°æ®é…ç½®æ–‡ä»¶è§ "theme/_cdn.yml"
    # å˜é‡è¯´æ˜ï¼š
    # ä»¥ä¸‹å˜é‡åªèƒ½åœ¨ `prefix` ä¸­ä½¿ç”¨ã€‚
    # ${site_root}                ç«™ç‚¹æ ¹ç›®å½• ä¸€èˆ¬æ˜¯ "/"
    # ä»¥ä¸‹å˜é‡åªèƒ½åœ¨ `format` ä¸­ä½¿ç”¨ã€‚
    # ${prefix}                   CDN é“¾æ¥å‰ç¼€
    # ${name}                     package åç§° è§ "theme/_cdn.yml"
    # ${version}                  package ç‰ˆæœ¬ è§ "theme/_cdn.yml"
    # ${file}                     æ–‡ä»¶è·¯å¾„ è§ "theme/_cdn.yml"
    # ${min_file}                 æ–‡ä»¶è·¯å¾„ ${file} åæ·»åŠ  .min. (jsdelivrã€cdnjs å®˜æ–¹è‡ªå¸¦å‹ç¼©)
    # ${timestamp}                Hexoè¿è¡Œæ—¶çš„æ—¶é—´æˆ³(egï¼š1661246702300), å¯ç”¨äºé™æ€èµ„æºç‰ˆæœ¬æ§åˆ¶ format: ${prefix}${file}?v=${timestamp}
    system_config:
        # è‡ªå®šä¹‰é…ç½® ä½¿ç”¨ "theme/_cdn.yml" ä¸­çš„åç§°ä½œä¸ºé…ç½®é¡¹çš„é”®
        custom:
            #simple_style: /css/index.css
            #simple_app: /js/app.js

        # ä¸»é¢˜ /jsä¸/cssç›®å½• ï¼ˆä¸€èˆ¬æ”¾åœ¨æœ¬åœ°ï¼Œå¯ä»¥åœ¨æ­¤å¤„é…ç½®ç«™ç‚¹CDNï¼‰,"theme/_cdn.yml" ä¸­ä»¥ "simple_" å¼€å¤´çš„åç§°
        # Tip: åœ¨æœ¬é…ç½®æ–‡ä»¶ä¸­ åŒ¹é…ä»¥ "simple-local" å¼€å¤´çš„é“¾æ¥è·¯å¾„æ›¿æ¢ä¸ºè¯¥æ ¼å¼çš„å‰ç¼€å¼€å¤´ prefix
        local:
            # CDN é“¾æ¥å‰ç¼€
            prefix: ${site_root}
            # local CDN æ ¼å¼
            format: ${prefix}${file}

        # npm
        # https://www.npmjs.com/
        # Tip: åœ¨æœ¬é…ç½®æ–‡ä»¶ä¸­ åŒ¹é…ä»¥ "simple-npm" å¼€å¤´çš„é“¾æ¥è·¯å¾„æ›¿æ¢ä¸ºè¯¥æ ¼å¼çš„å‰ç¼€å¼€å¤´ prefix
        npm:
            prefix: https://unpkg.com
            format: ${prefix}/${name}@${version}/${file}

        # cdnjs
        # https://cdnjs.com/
        # Tip: åœ¨æœ¬é…ç½®æ–‡ä»¶ä¸­ åŒ¹é…ä»¥ "simple-cdnjs" å¼€å¤´çš„é“¾æ¥è·¯å¾„æ›¿æ¢ä¸ºè¯¥æ ¼å¼çš„å‰ç¼€å¼€å¤´ prefix
        cdnjs:
            prefix: https://cdn.bootcdn.net/ajax/libs
            format: ${prefix}/${name}/${version}/${min_file}

plugins:
    # fontawesome
    fontawesome: true # true | false
